services:
  db:
    image: postgres:15-alpine
    container_name: calai-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calai
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:15-alpine
    container_name: calai-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calai_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
